name: appanimales
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  firebase_auth: ^4.15.0
  firebase_analytics: ^10.7.2
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.3
  image_picker: ^1.0.4
  firebase_storage: ^11.5.3
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  flutter_map: ^6.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/perro.jpeg
    - assets/gato.jpeg

