// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB40xxu7lHeF2VgpRYgAhrdF149MvsDVC8',
    appId: '1:739961319251:web:152208a29e4c09a563fba6',
    messagingSenderId: '739961319251',
    projectId: 'dondeestamimascota-38267',
    authDomain: 'dondeestamimascota-38267.firebaseapp.com',
    storageBucket: 'dondeestamimascota-38267.appspot.com',
    measurementId: 'G-M7PTXTS4B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXecycxqe_WgN34_H0zq3WIwnGrrSqiqE',
    appId: '1:739961319251:android:24a3e022f7a37d6f63fba6',
    messagingSenderId: '739961319251',
    projectId: 'dondeestamimascota-38267',
    storageBucket: 'dondeestamimascota-38267.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE_NqTNYXPVrhDuwmi6LiJ7dAst88X3S8',
    appId: '1:739961319251:ios:6cb080b5fabeeba463fba6',
    messagingSenderId: '739961319251',
    projectId: 'dondeestamimascota-38267',
    storageBucket: 'dondeestamimascota-38267.appspot.com',
    iosBundleId: 'com.example.appanimales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE_NqTNYXPVrhDuwmi6LiJ7dAst88X3S8',
    appId: '1:739961319251:ios:a0ce1195664070dd63fba6',
    messagingSenderId: '739961319251',
    projectId: 'dondeestamimascota-38267',
    storageBucket: 'dondeestamimascota-38267.appspot.com',
    iosBundleId: 'com.example.appanimales.RunnerTests',
  );
}
